[package]
name = "earf-rs"
version = "0.1.0"
authors = ["Louis Acresti <louis.acresti@gmail.com>"]
edition = "2018"

[dependencies]
impl_ops = "0.1.1"
rayon = "1.3.0"

[dependencies.sdl2]
version = "0.34.0"
default-features = false
features = ["image"]
